In [1]:
pip install numpy

     |████████████████████████████████| 17.1 MB 6.9 MB/s eta 0:00:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
from numpy import int64

In [4]:
array = np.array([1,2,3])

In [5]:
array.astype(dtype=float)

array([1., 2., 3.])

In [6]:
array

array([1, 2, 3])

In [7]:
array2 = array.copy()

In [8]:
array2.fill(0)  #Sustituye todos los valores por "0"
array2

array([0, 0, 0])

In [9]:
array.dump("datos.pk")  #Convierte los datos en un archivo binario

In [11]:
x = np.load("datos.pk", allow_pickle=True)  #Devuelve el archivo convertido en binario
x

array([1, 2, 3])

In [12]:
array.dumps()   #Devuelve el pickle de la matriz como una cadena

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X\x18\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [6]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=int64)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array = array.flatten() #Devuelve una copia de la matriz en una dimensión.
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
array.item(4)   #Devuelve la posicion en que se encuentre el valor

5

In [11]:
array = np.array([0,1,0,3,4,0], dtype=int64)    #Muestra los indices donde no vienen los "0"
array.nonzero()

(array([1, 3, 4]),)

In [22]:
array = np.array([1,4,3],dtype=int64)
array.prod(initial=3)   #Devuelve el producto de la matriz

36

In [19]:
array.put(1,4)
array

array([1, 4, 3])

In [45]:
array = np.array([1,2,3],dtype=int64)
array = array.repeat(repeats=3) #Repite el numero de veces los valores de la matriz
array.reshape(1,9)  #Toma forma dependiendo de los valores

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [49]:
array = np.array([[1,2],[3,4]],dtype=int64)
array


array([[1, 2],
       [3, 4]])

In [57]:
np.resize(array,(3,2))  #Cambie la forma y el tamaño de la matriz en el lugar.

array([[1, 2],
       [3, 4],
       [1, 2]])

In [58]:
array = np.array([[1,2,3],[4,1,2],[3,4,1],[2,3,4]],dtype=int64)
array

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1],
       [2, 3, 4]])

In [60]:
array.sort(axis=1, kind='quicksort')    #Rows
array

array([[1, 2, 3],
       [1, 2, 4],
       [1, 3, 4],
       [2, 3, 4]])

In [61]:
array.sort(axis=0, kind='quicksort')    #Cols
array

array([[1, 2, 3],
       [1, 2, 4],
       [1, 3, 4],
       [2, 3, 4]])

In [62]:
array = np.array([[0,1],[2,3]],dtype=int64)
array

array([[0, 1],
       [2, 3]])

In [63]:
array.swapaxes(1,0)     #Intercambia ejes

array([[0, 2],
       [1, 3]])

In [73]:
array = np.array([1,2,3,4,5],dtype=int64)
array


array([1, 2, 3, 4, 5])

In [75]:
array.take([2,4])    #Imprime los valores en el indice que se encuentra

array([3, 5])