<a href="https://colab.research.google.com/github/Ignacio246/colab/blob/main/04_10_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [42]:
import numpy as np
from numpy import int64, int32, zeros

In [4]:
np.__version__

'1.21.6'

## Numero de dimensiones
array.ndim

##Numero de caracteres

In [18]:
lista = [1,2,3,4,3]
array = np.array(lista)

#array.ndim #Numero de dimensiones

#array.shape #Numero de caracteres

#array.size #Cuantos elementos tiene

#array.dtype #Tipo de dato

#array.itemsize #El numero de bits que esta ocupando los valores

#array.data #Ubicacion en la memoria donde esta ubicado´
#type(array)

#array.max()
array.min()

1

In [25]:
lista1=[1,2,3]
lista2=[4,5,6]
array = np.array([lista1,lista2])
array.shape

(2, 3)

In [38]:
lista1=[1,2,]
lista2=[3,4,5]
lista3=[6,7,8,9]
array = np.array([lista1],dtype=int64)
array

array([[1, 2]])

In [39]:
#Simula un For
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [40]:
np.arange(5,10,3)

array([5, 8])

In [44]:
#Genera un arregolo de solo 0'
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
#Genera un arrelo de solo 1'
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
#Generar "n" numeros en un rango de "n" valores 
np.linspace(0,9,3)

array([0. , 4.5, 9. ])