<a href="https://colab.research.google.com/github/Ignacio246/colab/blob/main/07_10_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np

In [13]:
a = np.array(["unos","dos dos","tres"])
np.char.center(a,10,"-")

array(['---unos---', '-dos dos--', '---tres---'], dtype='<U10')

In [6]:
np.char.count(a,"s") #Contara el numero de caractres que le indiquemos

array([0, 1, 1])

In [8]:
np.char.find(a,"os")  #Dvolvera la posicion donde se encuntre el caracter de izquierda a derecha

array([-1,  1, -1])

In [11]:
np.char.rfind(a,"os") #Empieza a buscar caracteres de Derecha a izquierda

array([-1,  5, -1])

In [14]:
np.char.index(a,"s")  #Devuelve el index que busca izquierda a Derecha

array([3, 2, 3])

In [15]:
np.char.rindex(a,"s")   #Empieza a buscar de Derecha a izquierda

array([3, 6, 3])

In [18]:
a = np.array(["Hola","3","Hola3","\t"])

In [19]:
np.char.isalnum(a)  #Nos devuelve solo los valores que sean de tipo string

array([ True,  True,  True, False])

In [21]:
np.char.isalpha(a)  #

array([ True, False, False, False])

In [22]:
np.char.isdecimal(a)  #Devuelve solo si hay datos decimales

array([False,  True, False, False])

In [23]:
np.char.isnumeric(a)  #Devuelve solo si hay datos numericos

array([False,  True, False, False])

In [24]:
np.char.isspace(a)  #Devuelve solo si hay espacios

array([False, False, False,  True])

In [25]:
np.char.istitle(a)  #Si la primer letra es mayuscula

array([ True, False,  True, False])